[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max-old-space-size=4096"

# SEO friendly redirects
[[redirects]]
  from = "/jobs/*"
  to = "/is-ilanlari/:splat"
  status = 301

[[redirects]]
  from = "/job/*"
  to = "/ilan/:splat"
  status = 301

[[redirects]]
  from = "/career/*"
  to = "/kariyer/:splat"
  status = 301

# PayTR Callback URL
[[redirects]]
  from = "/api/paytr-callback"
  to = "/.netlify/functions/paytr-callback"
  status = 200
  force = true

# Dynamic Job Sitemap - MUST be before any wildcard redirects
[[redirects]]
  from = "/sitemap-jobs.xml"
  to = "/.netlify/functions/sitemap-jobs"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

# Robots.txt
[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

# Ana SPA yönlendirmesi (en sonda olmalı)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ✅ GÜVENLİK VE PERFORMANS HEADER'LARI (LIGHTHOUSE İÇİN KRİTİK)
[[headers]]
  for = "/*"
  [headers.values]
    # Güvenlik Headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # HSTS - HTTPS zorunlu kılar
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Cross-Origin-Opener-Policy (Lighthouse için gerekli)
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    
    # Cross-Origin-Embedder-Policy
    Cross-Origin-Embedder-Policy = "unsafe-none"
    
    # Content Security Policy (CSP) - DÜZELTILMIŞ: data: blob: eklendi
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob: https://www.googletagmanager.com https://www.google-analytics.com https://accounts.google.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: https: blob:; connect-src 'self' https://www.google-analytics.com https://*.firebaseio.com https://*.googleapis.com https://firebasestorage.googleapis.com https://identitytoolkit.googleapis.com https://securetoken.googleapis.com https://www.paytr.com; frame-src 'self' https://accounts.google.com; worker-src 'self' blob:; manifest-src 'self'; media-src 'self' https:; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none';"
    
    # Permissions Policy
    Permissions-Policy = "accelerometer=(), ambient-light-sensor=(), autoplay=(self), battery=(), camera=(), display-capture=(), document-domain=(), encrypted-media=(), fullscreen=(self), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(self), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=()"
    
    # SEO Headers
    X-Robots-Tag = "index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1"
    X-UA-Compatible = "IE=edge"
    X-DNS-Prefetch-Control = "on"
    Link = "</sitemap.xml>; rel=sitemap; type=application/xml"

# XML Sitemaps için özel headers
[[headers]]
  for = "/sitemap*.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=3600, s-maxage=3600"
    X-Robots-Tag = "index, follow"
    Link = "</sitemap.xml>; rel=sitemap; type=application/xml"
    Access-Control-Allow-Origin = "*"

# JavaScript dosyaları - Uzun süreli cache (Netlify otomatik sıkıştırır)
[[headers]]
  for = "/assets/js/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# CSS dosyaları - Uzun süreli cache (Netlify otomatik sıkıştırır)
[[headers]]
  for = "/assets/css/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Font dosyaları - Uzun süreli cache
[[headers]]
  for = "/assets/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Görseller - Uzun süreli cache
[[headers]]
  for = "/assets/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/svg+xml"

# HTML - Kısa cache
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    
# Service Worker - No cache
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Manifest
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/manifest+json"
