[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-sitemap"

[plugins.inputs]
  buildDir = "dist"
  prettyURLs = true
  trailingSlash = false
  changeFreq = "daily"
  priority = 0.8
  exclude = [
    '**/404*',
    '**/giris*',
    '**/kayit*',
    '**/hesap-ayarlari*',
    '**/ilanlarim*',
    '**/admin*'
  ]

# Sitemap yönlendirmeleri
[[redirects]]
  from = "/sitemap-jobs.xml"
  to = "/.netlify/functions/sitemap-jobs"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

# Ana SPA yönlendirmesi (en sonda olmalı)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for XML files - CRITICAL for sitemap recognition
[[headers]]
  for = "/sitemap*.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=3600"
    X-Robots-Tag = "noindex"
    Access-Control-Allow-Origin = "*"

# Headers for better SEO and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"